### ISSUE TITLE
US16 - Contar Quantidade de Medicamentos

### ISSUE THREAD

**Issue by vinicinolivera** [pi1-2018-2-c/PI1_2018_2#27]
Eu, como usuário, desejo verificar a quantidade de medicamentos que estão disponíveis.

https://github.com/zero101010/PI1_2018_2/wiki/UC16-Contar-Quantidade-de-Medicamentos

**Comment by cantuariavc** [comment]
https://github.com/pi1-2018-2-c/PI1_2018_2/commit/5bc1e5ff4f5c0022eabc902d40ecca62a423a9ca
