### ISSUE TITLE
US14 - Restringir Horário da Medicação

### ISSUE THREAD

**Issue by vinicinolivera** [pi1-2018-2-c/PI1_2018_2#28]
Eu, como usuário, desejo que o sistema limite o tempo para tomar um medicamento.

https://github.com/zero101010/PI1_2018_2/wiki/UC14-Restringir-Horário-da-Medicação

**Comment by cantuariavc** [comment]
https://github.com/pi1-2018-2-c/PI1_2018_2/commit/5bc1e5ff4f5c0022eabc902d40ecca62a423a9ca
