### ISSUE TITLE
US15 - Informar Status do Medicamento

### ISSUE THREAD

**Issue by vinicinolivera** [pi1-2018-2-c/PI1_2018_2#29]
Eu, como usuário, desejo que o sistema mostra se o medicamento foi resgatado.

https://github.com/zero101010/PI1_2018_2/wiki/UC15-Informar-Status-do-Medicamento

**Comment by cantuariavc** [comment]
https://github.com/pi1-2018-2-c/PI1_2018_2/commit/5bc1e5ff4f5c0022eabc902d40ecca62a423a9ca
