### ISSUE TITLE
US13 - Informar Horários dos Medicamentos

### ISSUE THREAD

**Issue by vinicinolivera** [pi1-2018-2-c/PI1_2018_2#30]
Eu, como usuário, desejo tomar todos os remédios em seus respectivos horários, e para isso, o sistema deve me avise quando estiver na hora.

https://github.com/zero101010/PI1_2018_2/wiki/UC13-Informar-Horários-dos-Medicamentos

**Comment by cantuariavc** [comment]
https://github.com/pi1-2018-2-c/PI1_2018_2/commit/5bc1e5ff4f5c0022eabc902d40ecca62a423a9ca
